### ISSUE TITLE
Problem using SnapService with GeoFenceTransitions

### ISSUE THREAD

**Issue by heitorpr** [mindbirth/snap-services#10]
Guys I'm trying to use your lib to implement an old intentService of Geofence transitions, but when I use your method I cant get the GeofencingEvent on service.

```SnapServicesContext.generatePendingIntentForService(getApplicationContext(), intent, 0);```

Using this to retrieve the GeofencingEvent:

```GeofencingEvent.fromIntent(intent);```

I get an empty GeofencingEvent... it returns but all params are null.. Any idea to help? =)

**Comment by mindbirth** [comment]
That will not work because the pending intent that's passed to the GeofencingClient - which is the one that's probably modified by that api - is not the one that's delivered to you.

You need to have your own middle layer that will then redirect to your Snap Service for handling.

In any case, I think you still need to do this because with Android O you wouldn't be able to launch android services while in background.

So, I propose you create a PendingIntent for a broadcast receiver. Then, inside you GeofencingEvent.fromIntent(intent) from the received intent and bundle that inside your own Intent that will then be used to start the SnapService you have designated to handle such work in background.

Let me know how it goes ;)
